/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edext.presentacion;

import com.edext.logica.Fabrica;
import com.edext.logica.IControlador;
import java.util.List;
import javax.swing.JOptionPane;
import com.edext.datatypes.DTPrograma;
import com.edext.datatypes.DtCurso;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pipo
 */
public class agregarCursoPrograma extends javax.swing.JPanel {

    /**
     * Creates new form AgregarCursoPrograma
     */
    public agregarCursoPrograma() {
        initComponents();
        cargarProgramas();
        cargarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPrograma = new javax.swing.JComboBox<>();
        lblPrograma = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        lblCurso = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        lblSeleccionarCurso = new javax.swing.JLabel();

        cbPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbPrograma.addActionListener(this::cbProgramaActionPerformed);

        lblPrograma.setText("Seleccionar Programa de Formacion:");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A1", null, null, null, null, null, null, null},
                {"A2", null, null, null, null, null, null, null},
                {"A3", null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Duracion", "Horas", "Creditos", "Registro", "URL", "Previas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        lblCurso.setText("Curso seleccionado:");

        txtCurso.setEditable(false);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        lblSeleccionarCurso.setText("Seleccionar curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPrograma)
                                .addGap(18, 18, 18)
                                .addComponent(cbPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSeleccionarCurso))
                        .addGap(0, 126, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCurso)
                        .addGap(18, 18, 18)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(btnAgregar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrograma))
                .addGap(27, 27, 27)
                .addComponent(lblSeleccionarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(0, 14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int filaSeleccionada = tbl.getSelectedRow();
        
        if (filaSeleccionada != -1){
            String curso = tbl.getValueAt(filaSeleccionada,0).toString();
            txtCurso.setText(curso);
        }
    }//GEN-LAST:event_tblMouseClicked

    private void cbProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgramaActionPerformed
        cargarCursos();
    }//GEN-LAST:event_cbProgramaActionPerformed

    private void cargarProgramas(){
        try{
            IControlador ic = Fabrica.getInstance().getIControlador();
            List<DTPrograma> lista = ic.listarProgramas();
            cbPrograma.removeAllItems();
            for (DTPrograma aux : lista){
                cbPrograma.addItem(aux.getNombre());
            }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al obtener lista de Programas de Formacion: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarCursos(){
        try{
            txtCurso.setText(""); 
            
            IControlador ic = Fabrica.getInstance().getIControlador();
            List<DtCurso> lista = ic.listarCursos();
            DefaultTableModel model = (DefaultTableModel) tbl.getModel();
            model.setRowCount(0);
            for (DtCurso aux: lista){               
                String strPrevias = (aux.getPrevias() != null && !aux.getPrevias().isEmpty()) 
                                        ? String.join(", ", aux.getPrevias()) 
                                        : "---";
                
                model.addRow(new Object[]{
                        aux.getNombre(),
                        aux.getDescripcion(),
                        aux.getDuracion(),
                        aux.getCantidadHoras(),
                        aux.getCreditos(),
                        aux.getFechaRegistro(),
                        aux.getUrl(),
                        strPrevias
                    });   
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al obtener Cursos: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            
            if (cbPrograma.getItemCount() < 0){
                //Si no hay ningun programa creado, no hay donde agregar un curso.
                return;
            }
            
            String programa = cbPrograma.getSelectedItem().toString();
            String curso = txtCurso.getText().trim();
        
            if (curso.isEmpty()||programa.isEmpty()){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un curso y un Programa de Formacion validos", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            IControlador ic = Fabrica.getInstance().getIControlador();
            ic.agregarProgramaCurso(programa, curso);
            
            JOptionPane.showMessageDialog(this, "Curso '"+curso+"' agregado con éxito al programa de formacion '"+programa+"'.","Éxito",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error al agregar curso a programa de formacion: "+e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cbPrograma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblPrograma;
    private javax.swing.JLabel lblSeleccionarCurso;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCurso;
    // End of variables declaration//GEN-END:variables
}
