/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edext.presentacion;

import com.edext.datatypes.DtInstituto;
import com.edext.datatypes.DtUsuario;
import com.edext.datatypes.TipoUsuario;
import com.edext.logica.Fabrica;
import com.edext.logica.GestorImagenes;
import com.edext.logica.IControlador;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;//para que no de error al cargar el formulario la imagen generica por el ancho
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author usuario
 */
public class AltaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form AltaUsuarioN
     */
    
    private File imagenSeleccionada;
    
    public AltaUsuario() {
        initComponents();
        imagenSeleccionada = new File ("imagenes/usr.png");
        lblInstituto.setVisible(false);
        cbInstitutos.setVisible(false);
        btnAgregarInstituto.setVisible(false);
        btnQuitarInstituto.setVisible(false);
        lisInstitutos.setVisible(false);
        btnGuardarCambios.setVisible(false);
        scpInstituos.setVisible(false);
        cargarInstitutos();
        
        DefaultListModel<String> model = new DefaultListModel<>();
        lisInstitutos.setModel(model);
        SwingUtilities.invokeLater(() -> {cargarImagen("usr.png");}); 
    }
    // Constructor i = 1 ModificarUsuario , i = 2 ConsultaUsuario
    public AltaUsuario(int i) {
        initComponents();
        
        lblInstituto.setVisible(false);
        cbInstitutos.setVisible(false);
        txtNickname.setEnabled(false);
        btnAceptar.setVisible(false);
        txtEmail.setEnabled(false);
        chbDocente.setVisible(false);
        lisInstitutos.setVisible(false);
        btnAgregarInstituto.setVisible(false);
        btnQuitarInstituto.setVisible(false);
        scpInstituos.setEnabled(false);
        cbInstitutos.setEnabled(false);
        btnAgregarInstituto.setVisible(false);
        btnQuitarInstituto.setVisible(false);
        lisInstitutos.setEnabled(false);
        
        DefaultListModel<String> model = new DefaultListModel<>();
        lisInstitutos.setModel(model);
        
        cargarInstitutos();
        if (i ==2){  
            //Falta Obtener Cursos y cargar en las Tablas correspondientes
            txtApellido.setEnabled(false);
            txtNombre.setEnabled(false);
            dchFechaDeNacimiento.setEnabled(false);
            btnGuardarCambios.setVisible(false);
            btnAgregarImagen.setVisible(false);
            btnCancelar.setText("Volver");

        }
        
    }
    //carga una imagen generica de usuario en el formulario
    private void cargarImagen(String s) {
        
        File imagenSeleccionada = new File("imagenes",s);

        ImageIcon icono = new ImageIcon(imagenSeleccionada.getAbsolutePath());

        Image imagen = icono.getImage();

        Image imagenEscalada = imagen.getScaledInstance(
            lblImagen.getWidth(),
            lblImagen.getHeight(),
            Image.SCALE_SMOOTH
        );

        lblImagen.setIcon(new ImageIcon(imagenEscalada));
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        chbDocente = new javax.swing.JCheckBox();
        dchFechaDeNacimiento = new com.toedter.calendar.JDateChooser();
        lblInstituto = new javax.swing.JLabel();
        cbInstitutos = new javax.swing.JComboBox<>();
        lblNickname = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnAgregarImagen = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();
        scpInstituos = new javax.swing.JScrollPane();
        lisInstitutos = new javax.swing.JList<>();
        btnAgregarInstituto = new javax.swing.JButton();
        btnQuitarInstituto = new javax.swing.JButton();

        txtApellido.addActionListener(this::txtApellidoActionPerformed);

        chbDocente.setText("Docente");
        chbDocente.addActionListener(this::chbDocenteActionPerformed);

        dchFechaDeNacimiento.setDateFormatString("d M y");
        dchFechaDeNacimiento.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        dchFechaDeNacimiento.setMaxSelectableDate(new java.util.Date(1798776104000L));

        lblInstituto.setText("Instituto");

        lblNickname.setText("Nickname");

        lblNombre.setText("Nombre");

        lblApellido.setText("Apellido");

        lblEmail.setText("Email");

        lblFechaDeNacimiento.setText("Fecha de Nacimiento");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        lblImagen.setBackground(new java.awt.Color(102, 204, 255));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnAgregarImagen.setText("Agregar Imagen");
        btnAgregarImagen.addActionListener(this::btnAgregarImagenActionPerformed);

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.addActionListener(this::btnGuardarCambiosActionPerformed);

        scpInstituos.setViewportView(lisInstitutos);

        btnAgregarInstituto.setText("=>");
        btnAgregarInstituto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarInstituto.addActionListener(this::btnAgregarInstitutoActionPerformed);

        btnQuitarInstituto.setText("X");
        btnQuitarInstituto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuitarInstituto.addActionListener(this::btnQuitarInstitutoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFechaDeNacimiento)
                                        .addGap(6, 6, 6)
                                        .addComponent(dchFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addComponent(lblApellido))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNickname)
                                            .addComponent(txtNombre))
                                        .addGap(35, 35, 35))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarImagen)
                            .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCambios))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbDocente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblInstituto)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbInstitutos, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnAgregarInstituto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(scpInstituos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitarInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblNickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(lblApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNickname)
                                .addGap(11, 11, 11)
                                .addComponent(txtNombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellido)))
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFechaDeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(dchFechaDeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAgregarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(48, 48, 48)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(cbInstitutos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarInstituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scpInstituos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnQuitarInstituto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cargarInstitutos() {
        try {
            IControlador ic = Fabrica.getInstance().getIControlador();

            List<DtInstituto> lista = ic.listarInstitutos();

            cbInstitutos.removeAllItems();

            for (DtInstituto aux : lista) {
                cbInstitutos.addItem(aux.getNombre());
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al cargar los institutos: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed
    //Mostrar Institutos solo si el nuevo usuario es docente
    private void chbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDocenteActionPerformed
      
        mostrarInstitutos(chbDocente.isSelected());

    }//GEN-LAST:event_chbDocenteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        javax.swing.JInternalFrame frame = 
        (javax.swing.JInternalFrame) javax.swing.SwingUtilities.getAncestorOfClass(javax.swing.JInternalFrame.class, this);
        frame.dispose();       
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        String nickname = txtNickname.getText().trim();
        String email = txtEmail.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();

        Date fNacimiento = dchFechaDeNacimiento.getDate();

        if ((fNacimiento == null)  || nombre.isEmpty() || apellido.isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "Debe completar todos los campos.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        List<String> institutos = new ArrayList<>();
        
        TipoUsuario tipo;
        
        DefaultListModel<String> model = (DefaultListModel<String>) lisInstitutos.getModel();
        
        if (chbDocente.isSelected()) {
            tipo = TipoUsuario.DOCENTE;
            
            if (model.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "El docente debe tener al menos un instituto.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            
            for (int i = 0; i < model.getSize(); i++) {
                institutos.add(model.getElementAt(i));
            }
            
        } else {
            tipo = TipoUsuario.ESTUDIANTE;
        }

        try {

            String imagen = GestorImagenes.guardarImagen(imagenSeleccionada,nickname);

    

            DtUsuario usuarioModificado = new DtUsuario(
                nickname,
                email,
                nombre,
                apellido,
                imagen,
                fNacimiento,
                institutos,
                tipo
            );

            IControlador ic = Fabrica.getInstance().getIControlador();

            ic.modificarUsuario(usuarioModificado);

            JOptionPane.showMessageDialog(
                this,
                "Usuario modificado correctamente.",
                "Modificar usuario",
                JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(
                this,
                ex.getMessage(),
                "ERROR",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    public void limpiarCampos() {
        txtNickname.setText("");
        txtEmail.setText("");
        txtNombre.setText("");
        txtApellido.setText("");

        dchFechaDeNacimiento.setDate(null);

        chbDocente.setSelected(false);

        cbInstitutos.setSelectedIndex(0);
        
        lisInstitutos.setVisible(false);
        btnAgregarInstituto.setVisible(false);
        btnQuitarInstituto.setVisible(false);
        scpInstituos.setVisible(false);
        lblInstituto.setVisible(false);
        cbInstitutos.setVisible(false);
        
        
        ((DefaultListModel<String>) lisInstitutos.getModel()).clear();

        cargarImagen("usr.png");
    }
    
    private void mostrarInstitutos(boolean mostrar) {
        lblInstituto.setVisible(mostrar);
        cbInstitutos.setVisible(mostrar);
        btnAgregarInstituto.setVisible(mostrar);
        btnQuitarInstituto.setVisible(mostrar);
        lisInstitutos.setVisible(mostrar);
        scpInstituos.setVisible(mostrar);

        revalidate();
        repaint();

    }
    public void cargarFormulario (DtUsuario usuario){
        txtNickname.setText(usuario.getNickname());
        txtEmail.setText(usuario.getEmail());
        txtNombre.setText(usuario.getNombre());
        txtApellido.setText(usuario.getApellido());
        dchFechaDeNacimiento.setDate(usuario.getfNacimiento());

        chbDocente.setEnabled(false);

        DefaultListModel<String> model =
                (DefaultListModel<String>) lisInstitutos.getModel();

        if (usuario.getTipoUsuario() == TipoUsuario.DOCENTE) {

            chbDocente.setVisible(true);
            chbDocente.setSelected(true);

            lblInstituto.setVisible(true);
            cbInstitutos.setVisible(true);
            lisInstitutos.setVisible(true);
            scpInstituos.setVisible(true);
            btnAgregarInstituto.setVisible(true);
            btnQuitarInstituto.setVisible(true);

            for (String instituto : usuario.getInstitutos()) {
                model.addElement(instituto);
            }

        } else {

            chbDocente.setVisible(false);

            lblInstituto.setVisible(false);
            cbInstitutos.setVisible(false);
            lisInstitutos.setVisible(false);
            scpInstituos.setVisible(false);
            btnAgregarInstituto.setVisible(false);
            btnQuitarInstituto.setVisible(false);
        }

        cargarImagen(usuario.getImagen());

        imagenSeleccionada =
                new File("imagenes", usuario.getImagen()); 
    }
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        IControlador ic = Fabrica.getInstance().getIControlador();
        String nickname = txtNickname.getText().trim();
        String email = txtEmail.getText().trim();
        String nombre = txtNombre.getText().trim();
        String apellido = txtApellido.getText().trim();

        Date fNacimiento = dchFechaDeNacimiento.getDate();

        // Validar campos de texto
        if (nickname.isEmpty() || email.isEmpty()
                || nombre.isEmpty() || apellido.isEmpty()) {

            JOptionPane.showMessageDialog(this,"Debe completar todos los campos obligatorios.","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar fecha
        if (fNacimiento == null) {
            JOptionPane.showMessageDialog(this,"Debe seleccionar una fecha de nacimiento.", "Error",JOptionPane.ERROR_MESSAGE );
            return;
        }

        List<String> institutos = new ArrayList<>();
        TipoUsuario tipo;

        if (chbDocente.isSelected()) {
            tipo = TipoUsuario.DOCENTE;
            DefaultListModel<String> model = (DefaultListModel<String>) lisInstitutos.getModel();

            for (int i = 0; i < model.getSize(); i++) {
                institutos.add(model.getElementAt(i));
            }
            
            if (institutos.isEmpty()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Debe seleccionar al menos un instituto.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

        } else {
            tipo = TipoUsuario.ESTUDIANTE;
        }
        
        
        
        try {
            if (ic.existeUsuario(nickname)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ya existe un usuario con el nickname '" + nickname + "'.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            if (ic.existeEmail(email)) {
                JOptionPane.showMessageDialog(
                        this,
                        "Ya existe un usuario con el email '" + email + "'.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            String imagen = GestorImagenes.guardarImagen(
                imagenSeleccionada,
                nickname
            );

            DtUsuario dtUsuario = new DtUsuario(
                nickname,
                email,
                nombre,
                apellido,
                imagen,
                fNacimiento,
                institutos,
                tipo
            );

            ic.crearUsuario(dtUsuario);
            limpiarCampos();
            JOptionPane.showMessageDialog(this,"Usuario creado correctamente.","Alta de usuario",JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this,ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAceptarActionPerformed
    //seleccionar imagen desde archivo
    private void btnAgregarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarImagenActionPerformed
        JFileChooser selector = new JFileChooser();
        
    
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes (PNG, JPG)","png", "jpg");
        selector.setFileFilter(filtro);
        int ancho = 124;
        int alto = 116;
        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {

            imagenSeleccionada = selector.getSelectedFile();

            ImageIcon icono = new ImageIcon(imagenSeleccionada.getAbsolutePath());

            Image imagen = icono.getImage();

            Image imagenEscalada = imagen.getScaledInstance(
                lblImagen.getWidth(),
                lblImagen.getHeight(),
                Image.SCALE_SMOOTH
            );

            lblImagen.setIcon(new ImageIcon(imagenEscalada));
            
                // Mantener el tamaño del JLabel
            lblImagen.setPreferredSize(
                    new java.awt.Dimension(ancho, alto)
            );
            lblImagen.setMinimumSize(
                    new java.awt.Dimension(ancho, alto)
            );
            lblImagen.setMaximumSize(
                    new java.awt.Dimension(ancho, alto)
            );

            revalidate();
            repaint();
        }        
    }//GEN-LAST:event_btnAgregarImagenActionPerformed

    private void btnAgregarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarInstitutoActionPerformed
        
        Object seleccionado = cbInstitutos.getSelectedItem();

        if (seleccionado == null) {
            return;
        }

        String instituto = seleccionado.toString();
        DefaultListModel<String> model = (DefaultListModel<String>) lisInstitutos.getModel();

        // Evitar duplicados
        if (!model.contains(instituto)) {
            model.addElement(instituto);
        }
    }//GEN-LAST:event_btnAgregarInstitutoActionPerformed

    
    
    private void btnQuitarInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarInstitutoActionPerformed
        int indice = lisInstitutos.getSelectedIndex();

        if (indice != -1) {
            DefaultListModel<String> model =
                (DefaultListModel<String>) lisInstitutos.getModel();

            model.remove(indice);
        }
    }//GEN-LAST:event_btnQuitarInstitutoActionPerformed

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAgregarImagen;
    private javax.swing.JButton btnAgregarInstituto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnQuitarInstituto;
    private javax.swing.JComboBox<String> cbInstitutos;
    private javax.swing.JCheckBox chbDocente;
    private com.toedter.calendar.JDateChooser dchFechaDeNacimiento;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblInstituto;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> lisInstitutos;
    private javax.swing.JScrollPane scpInstituos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
