package com.edext.presentacion;

import com.edext.tools.ArbolHelper;

/**
 *
 * @author vdraco
 */
public final class Arbol extends javax.swing.JPanel {

    /**
     * Creates new form Arbol
     */
    public Arbol() {
        initComponents();
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        jTree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTreeFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTreeFocusGained
        cargar();
    }//GEN-LAST:event_jTreeFocusGained
    
    private void cargar(){
        ArbolHelper tree=new ArbolHelper();
        jTree.setModel(tree.getModel());
        tree=null;
        for(int i = 0; i < jTree.getRowCount(); i++) jTree.expandRow(i);
    }
    
//    private void cargar(){
//        ArbolHelper tree=new ArbolHelper();
//        tree.createArbol(jTree);
//        tree=null;
//    }
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
