/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edext.presentacion;

import com.edext.tools.ArbolHelper;

/**
 *
 * @author vdraco
 */
public final class Arbol extends javax.swing.JPanel {

    /**
     * Creates new form Arbol
     */
    public Arbol() {
        initComponents();
        cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        jTree.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTreeFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTreeFocusGained
        cargar();
    }//GEN-LAST:event_jTreeFocusGained

    private void cargar(){
        ArbolHelper tree=new ArbolHelper();
        tree.createArbol(jTree);
        tree=null;
    }
    
    
    
// public void construirArbolJerarquico(JTree treeExplorador) {
//    try {
//        // 1. Nodo raíz del explorador
//        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Institutos de Educación");
//        
//        // 2. Listamos los institutos (usando tu IControlador)
//        List<DtInstituto> institutos = Fabrica.getInstance().getIControlador().listarInstitutos();
//        
//        for (DtInstituto inst : institutos) {
//            DefaultMutableTreeNode nodoInstituto = new DefaultMutableTreeNode(inst.getNombre());
//            raiz.add(nodoInstituto);
//            
//            // 3. Por cada instituto, colgamos sus cursos
//            List<String> cursos = Fabrica.getInstance().getIControlador().listarCursosPorInstituto(inst.getNombre());
//            
//            for (String curso : cursos) {
//                DefaultMutableTreeNode nodoCurso = new DefaultMutableTreeNode(curso);
//                nodoInstituto.add(nodoCurso);
//                
//                // 4. Usamos TU método blindado contra nulos para las ediciones
//                // Nota: Ajustá el nombre de tu método de clase según corresponda
//                List<String> ediciones = Fabrica.getInstance().getIControlador().listaEdicionPorCurso(curso); 
//                
//                for (String edicion : ediciones) {
//                    DefaultMutableTreeNode nodoEdicion = new DefaultMutableTreeNode(edicion);
//                    nodoCurso.add(nodoEdicion);
//                }
//            }
//        }
//        
//        // 5. Inyectamos el modelo cargado al JTree de Swing
//        treeExplorador.setModel(new DefaultTreeModel(raiz));
//        
//    } catch (Exception e) {
//        org.tinylog.Logger.error(e, "Error al construir el JTree jerárquico");
//        //JOptionPane.showMessageDialog(this, "No se pudo cargar el explorador visual: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
//}   
//    
//public void cargarExploradorVisual(javax.swing.JTree treeExplorador) {
//    try {
//        // 1. Nodo raíz principal
//        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Plataforma Educativa");
//        
//        // 2. Iteramos los institutos usando tu controlador
//        List<DtInstituto> institutos = Fabrica.getInstance().getIControlador().listarInstitutos();
//        for (DtInstituto inst : institutos) {
//            DefaultMutableTreeNode nodoInstituto = new DefaultMutableTreeNode(inst.getNombre());
//            raiz.add(nodoInstituto);
//            
//            // 3. Iteramos los cursos de ese instituto
//            List<String> cursos = Fabrica.getInstance().getIControlador().listarCursosPorInstituto(inst.getNombre());
//            for (String curso : cursos) {
//                DefaultMutableTreeNode nodoCurso = new DefaultMutableTreeNode(curso);
//                nodoInstituto.add(nodoCurso);
//                
//                // 4. Usamos TU método blindado contra nulos para colgar las ediciones
//                // Pasamos el nombre del curso actual para que busque sus ediciones
//                List<String> ediciones = Fabrica.getInstance().getIControlador().listaEdicionPorCurso(curso); 
//                for (String edicion : ediciones) {
//                    DefaultMutableTreeNode nodoEdicion = new DefaultMutableTreeNode(edicion);
//                    nodoCurso.add(nodoEdicion);
//                }
//            }
//        }
//        
//        // 5. Inyectamos el modelo cargado en el componente de Swing
//        treeExplorador.setModel(new DefaultTreeModel(raiz));
//        
//    } catch (Exception e) {
//        org.tinylog.Logger.error(e, "Error al rellenar el JTree con las ediciones");
//        JOptionPane.showMessageDialog(this, "Error al cargar el árbol: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//    }
//}


    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
