/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edext.presentacion;

import com.edext.datatypes.DtUsuario;
import com.edext.datatypes.TipoUsuario;
import com.edext.logica.Fabrica;
import com.edext.logica.IControlador;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ConsultaUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaUsuario
     */
    private AltaUsuario formularioUsuario;
    private List<DtUsuario> usuarios;
    
    public ConsultaUsuario() {
        initComponents();
        crearFormulario();
        
        listarUsuarios();
    }
    
    private void crearFormulario(){
        
        panUsuario.removeAll();
         
        formularioUsuario = new AltaUsuario(2);
        panUsuario.setLayout(new BorderLayout());
        panUsuario.add(formularioUsuario, BorderLayout.CENTER);
        panUsuario.revalidate();
        panUsuario.repaint();
    }
    
    private void listarUsuarios(){
        try{
            IControlador ic = Fabrica.getInstance().getIControlador();

            usuarios = ic.listarUsuarios();

            DefaultListModel<String> model = new DefaultListModel<>();

            for (DtUsuario aux: usuarios){
                model.addElement(aux.getNickname());
            }

            lisUsuario.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(
                this,
                "Error al actualizar la tabla: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within ttruehe constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpUsuarios = new javax.swing.JScrollPane();
        lisUsuario = new javax.swing.JList<>();
        panUsuario = new javax.swing.JPanel();
        tbCursosYProgramas = new javax.swing.JTabbedPane();
        panCursos = new javax.swing.JPanel();
        scpCursos = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        panEdicionesDeCursos = new javax.swing.JPanel();
        scpEdicionDeCursos = new javax.swing.JScrollPane();
        tblEdicionDeCursos = new javax.swing.JTable();
        panProgramas = new javax.swing.JPanel();
        scpProgramas = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lisUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lisUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lisUsuario.addListSelectionListener(this::lisUsuarioValueChanged);
        scpUsuarios.setViewportView(lisUsuario);

        javax.swing.GroupLayout panUsuarioLayout = new javax.swing.GroupLayout(panUsuario);
        panUsuario.setLayout(panUsuarioLayout);
        panUsuarioLayout.setHorizontalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        panUsuarioLayout.setVerticalGroup(
            panUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        tbCursosYProgramas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        panCursos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Duración", "Horas", "Créditos", "Fecha Registro", "URL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCursos.setColumnSelectionAllowed(true);
        scpCursos.setViewportView(tblCursos);
        tblCursos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout panCursosLayout = new javax.swing.GroupLayout(panCursos);
        panCursos.setLayout(panCursosLayout);
        panCursosLayout.setHorizontalGroup(
            panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        panCursosLayout.setVerticalGroup(
            panCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCursosLayout.createSequentialGroup()
                .addComponent(scpCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tbCursosYProgramas.addTab("Cursos", panCursos);
        panCursos.getAccessibleContext().setAccessibleName("");

        panEdicionesDeCursos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        tblEdicionDeCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Cupo", "Registrado", "Inicio", "Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEdicionDeCursos.setColumnSelectionAllowed(true);
        scpEdicionDeCursos.setViewportView(tblEdicionDeCursos);
        tblEdicionDeCursos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout panEdicionesDeCursosLayout = new javax.swing.GroupLayout(panEdicionesDeCursos);
        panEdicionesDeCursos.setLayout(panEdicionesDeCursosLayout);
        panEdicionesDeCursosLayout.setHorizontalGroup(
            panEdicionesDeCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpEdicionDeCursos, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        panEdicionesDeCursosLayout.setVerticalGroup(
            panEdicionesDeCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEdicionesDeCursosLayout.createSequentialGroup()
                .addComponent(scpEdicionDeCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tbCursosYProgramas.addTab("Ediciones de Cursos", panEdicionesDeCursos);

        panProgramas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Registro", "Inicio", "Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        scpProgramas.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout panProgramasLayout = new javax.swing.GroupLayout(panProgramas);
        panProgramas.setLayout(panProgramasLayout);
        panProgramasLayout.setHorizontalGroup(
            panProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpProgramas, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        panProgramasLayout.setVerticalGroup(
            panProgramasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProgramasLayout.createSequentialGroup()
                .addComponent(scpProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        tbCursosYProgramas.addTab("Programas", panProgramas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tbCursosYProgramas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tbCursosYProgramas, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lisUsuarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lisUsuarioValueChanged
  
        if (!evt.getValueIsAdjusting()) {

                int indice = lisUsuario.getSelectedIndex();
                crearFormulario();
                if (indice != -1) {
                    DtUsuario usuario = usuarios.get(indice);
                    
                    formularioUsuario.cargarFormulario(usuario);
                    if(usuario.getTipoUsuario()==TipoUsuario.ESTUDIANTE){
                        panCursos.setVisible(false);
                    }else{
                        panEdicionesDeCursos.setVisible(false);
                    }
                }
            } 

    }//GEN-LAST:event_lisUsuarioValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lisUsuario;
    private javax.swing.JPanel panCursos;
    private javax.swing.JPanel panEdicionesDeCursos;
    private javax.swing.JPanel panProgramas;
    private javax.swing.JPanel panUsuario;
    private javax.swing.JScrollPane scpCursos;
    private javax.swing.JScrollPane scpEdicionDeCursos;
    private javax.swing.JScrollPane scpProgramas;
    private javax.swing.JScrollPane scpUsuarios;
    private javax.swing.JTabbedPane tbCursosYProgramas;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTable tblEdicionDeCursos;
    // End of variables declaration//GEN-END:variables
}
