
package com.edext.presentacion;

import com.edext.tools.ConsultaEdicionHelper;
import com.edext.tools.Utils;
import javax.swing.DefaultComboBoxModel;
import org.tinylog.Logger;

/**
 *
 * @author vdraco
 */
public class ConsultaEdicionForm extends javax.swing.JPanel {

    /**
     * Creates new form consultaEdicionCurso
     */
    public ConsultaEdicionForm() {
        initComponents();
        //ConsultaEdicionHelper tmpSet=new ConsultaEdicionHelper();
        jPCursos.setVisible(false);
        jPEdiciones.setVisible(false);
        jPData.setVisible(false);
        cargaIntituto();
        //tmpSet=null;
        refreschCombo();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLInstituto = new javax.swing.JLabel();
        jCInstituto = new javax.swing.JComboBox();
        jPData = new javax.swing.JPanel();
        jLnombre = new javax.swing.JLabel();
        jLfechaFin = new javax.swing.JLabel();
        jLfechaInicio = new javax.swing.JLabel();
        jLcupo = new javax.swing.JLabel();
        jLcurso = new javax.swing.JLabel();
        jLfechaPublicacion = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jTFechaFin = new javax.swing.JTextField();
        jTFechaInicio = new javax.swing.JTextField();
        jTcupo = new javax.swing.JTextField();
        jTffechaPublicacion = new javax.swing.JTextField();
        jTcurso = new javax.swing.JTextField();
        jLdocente = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLdocentes = new javax.swing.JList<>();
        jPEdiciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLEdiciones = new javax.swing.JList<>();
        jPCursos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLCursos = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setMinimumSize(new java.awt.Dimension(637, 370));
        setPreferredSize(new java.awt.Dimension(637, 370));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLInstituto.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLInstituto.setText("Instituto ...:");
        add(jLInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 17, -1, -1));

        jCInstituto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jCInstituto.addItemListener(this::jCInstitutoItemStateChanged);
        jCInstituto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jCInstitutoComponentShown(evt);
            }
        });
        jCInstituto.addActionListener(this::jCInstitutoActionPerformed);
        add(jCInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 237, 34));

        jPData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnombre.setText("Nombre ..:");
        jLnombre.setFocusable(false);
        jPData.add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 15, -1, -1));

        jLfechaFin.setText("Fecha de Finalizacion .:");
        jLfechaFin.setFocusable(false);
        jPData.add(jLfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, -1, -1));

        jLfechaInicio.setText("Fecha de Inicio .....:");
        jLfechaInicio.setFocusable(false);
        jPData.add(jLfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 52, -1, -1));

        jLcupo.setText("Cupo .......:");
        jLcupo.setFocusable(false);
        jPData.add(jLcupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 124, -1, -1));

        jLcurso.setText("Curso ....:");
        jLcurso.setFocusable(false);
        jPData.add(jLcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 213, -1, -1));

        jLfechaPublicacion.setText("Fecha de Publicacion ...:");
        jLfechaPublicacion.setFocusable(false);
        jPData.add(jLfechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 171, -1, -1));

        jTnombre.setEditable(false);
        jTnombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTnombre.setFocusable(false);
        jTnombre.setMinimumSize(new java.awt.Dimension(230, 24));
        jTnombre.setPreferredSize(new java.awt.Dimension(230, 24));
        jTnombre.setRequestFocusEnabled(false);
        jTnombre.setVerifyInputWhenFocusTarget(false);
        jPData.add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 12, 180, -1));

        jTFechaFin.setEditable(false);
        jTFechaFin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFechaFin.setText("99/99/99");
        jTFechaFin.setFocusable(false);
        jTFechaFin.setMinimumSize(new java.awt.Dimension(85, 24));
        jTFechaFin.setPreferredSize(new java.awt.Dimension(85, 24));
        jTFechaFin.setRequestFocusEnabled(false);
        jTFechaFin.setVerifyInputWhenFocusTarget(false);
        jPData.add(jTFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 84, -1));

        jTFechaInicio.setEditable(false);
        jTFechaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFechaInicio.setText("99/99/99");
        jTFechaInicio.setFocusable(false);
        jTFechaInicio.setMinimumSize(new java.awt.Dimension(85, 24));
        jTFechaInicio.setPreferredSize(new java.awt.Dimension(85, 24));
        jTFechaInicio.setRequestFocusEnabled(false);
        jTFechaInicio.setVerifyInputWhenFocusTarget(false);
        jPData.add(jTFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 84, -1));

        jTcupo.setEditable(false);
        jTcupo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTcupo.setFocusable(false);
        jTcupo.setMinimumSize(new java.awt.Dimension(47, 24));
        jTcupo.setPreferredSize(new java.awt.Dimension(47, 24));
        jTcupo.setRequestFocusEnabled(false);
        jTcupo.setVerifyInputWhenFocusTarget(false);
        jPData.add(jTcupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 121, 57, -1));

        jTffechaPublicacion.setEditable(false);
        jTffechaPublicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTffechaPublicacion.setFocusable(false);
        jTffechaPublicacion.setMinimumSize(new java.awt.Dimension(85, 24));
        jTffechaPublicacion.setPreferredSize(new java.awt.Dimension(85, 24));
        jTffechaPublicacion.setRequestFocusEnabled(false);
        jTffechaPublicacion.setVerifyInputWhenFocusTarget(false);
        jTffechaPublicacion.addActionListener(this::jTffechaPublicacionActionPerformed);
        jPData.add(jTffechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 168, 84, -1));

        jTcurso.setEditable(false);
        jTcurso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTcurso.setFocusable(false);
        jTcurso.setMinimumSize(new java.awt.Dimension(99, 24));
        jTcurso.setPreferredSize(new java.awt.Dimension(105, 24));
        jTcurso.setRequestFocusEnabled(false);
        jTcurso.setVerifyInputWhenFocusTarget(false);
        jPData.add(jTcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 205, 160, -1));

        jLdocente.setText("Docente ...:");
        jLdocente.setFocusable(false);
        jPData.add(jLdocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, -1, -1));

        jLdocentes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jLdocentes.setFocusable(false);
        jLdocentes.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jLdocentes);

        jPData.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, 100));

        add(jPData, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 280, 350));

        jPEdiciones.setPreferredSize(new java.awt.Dimension(190, 270));
        jPEdiciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLEdiciones.setPreferredSize(new java.awt.Dimension(180, 360));
        jLEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEdicionesMouseClicked(evt);
            }
        });
        jLEdiciones.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jLEdicionesCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jLEdiciones);

        jPEdiciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 300));

        add(jPEdiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 54, 172, 308));

        jPCursos.setPreferredSize(new java.awt.Dimension(170, 260));
        jPCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jLCursos.setPreferredSize(new java.awt.Dimension(170, 24));
        jLCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCursosMouseClicked(evt);
            }
        });
        jLCursos.addListSelectionListener(this::jLCursosValueChanged);
        jScrollPane1.setViewportView(jLCursos);

        jPCursos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 300));

        add(jPCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 54, 152, 308));
    }// </editor-fold>//GEN-END:initComponents

    private void jCInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCInstitutoActionPerformed
        refreschCombo();
    }//GEN-LAST:event_jCInstitutoActionPerformed

    private void jLEdicionesCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jLEdicionesCaretPositionChanged
        
    }//GEN-LAST:event_jLEdicionesCaretPositionChanged

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void jCInstitutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCInstitutoItemStateChanged
        jPData.setVisible(false);
        jPEdiciones.setVisible(false);
        jPCursos.setVisible(true);
    }//GEN-LAST:event_jCInstitutoItemStateChanged

    private void jLCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCursosMouseClicked
        if(!jLCursos.getSelectedValuesList().isEmpty()){
            jLEdiciones.setListData((new ConsultaEdicionHelper()).getListaEdiciones(jLCursos.getSelectedValue()));
            jPEdiciones.setVisible(true);
        }else jPEdiciones.setVisible(false);
    }//GEN-LAST:event_jLCursosMouseClicked

    private void jLEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEdicionesMouseClicked
        if(!jLEdiciones.getSelectedValuesList().isEmpty()){
            loadData();
            jPData.setVisible(true);
        }else jPData.setVisible(false);
        
    }//GEN-LAST:event_jLEdicionesMouseClicked

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        jLEdiciones.getSelectedValuesList().clear();
    }//GEN-LAST:event_formComponentHidden

    private void jLCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLCursosValueChanged
        jPData.setVisible(false);
    }//GEN-LAST:event_jLCursosValueChanged

    private void jCInstitutoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jCInstitutoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jCInstitutoComponentShown

    private void jTffechaPublicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTffechaPublicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTffechaPublicacionActionPerformed

    private void loadData(){
        ConsultaEdicionHelper ceh=new ConsultaEdicionHelper();
        if(ceh.getData(jLEdiciones.getSelectedValue())){
            jTnombre.setText(ceh.getNombre());
            jTcupo.setText(Utils.Cast.valueOf(ceh.getCupo()));
            jTFechaInicio.setText(Utils.Fecha.assignFormato(ceh.getFechaInicio()));
            jTFechaFin.setText(Utils.Fecha.assignFormato(ceh.getFechaFin()));
            jTffechaPublicacion.setText(Utils.Fecha.assignFormato(ceh.getFechaPublicacion()));
            jTcurso.setText(ceh.getCurso());
            jLdocentes.setListData(ceh.getDocentes().toArray(String[]::new));
            //jTdocentej.setText(ceh.));
        }
    }
    private void refreschCombo(){
        ConsultaEdicionHelper tmpSet=new ConsultaEdicionHelper();
        String[] tmp=tmpSet.getListCursos(jCInstituto.getSelectedItem().toString());
        if(tmp.length==0) jPEdiciones.setVisible(false);
        jLCursos.setListData(tmp);
        jPCursos.setVisible(true);
        tmpSet=null;
    }
    private void cargaIntituto(){
        ConsultaEdicionHelper hlp=new ConsultaEdicionHelper();
        DefaultComboBoxModel<String> tmp=new DefaultComboBoxModel<>();
        String[] data=hlp.getListInstitutos();
        if(data.length>=0){
            for(String nom : data) tmp.addElement(nom);
            jCInstituto.setModel(tmp);
            jCInstituto.setSelectedIndex(0);
        }else Logger.debug("Intitutos sin datos...");

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCInstituto;
    private javax.swing.JList<String> jLCursos;
    private javax.swing.JList<String> jLEdiciones;
    private javax.swing.JLabel jLInstituto;
    private javax.swing.JLabel jLcupo;
    private javax.swing.JLabel jLcurso;
    private javax.swing.JLabel jLdocente;
    private javax.swing.JList<String> jLdocentes;
    private javax.swing.JLabel jLfechaFin;
    private javax.swing.JLabel jLfechaInicio;
    private javax.swing.JLabel jLfechaPublicacion;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JPanel jPCursos;
    private javax.swing.JPanel jPData;
    private javax.swing.JPanel jPEdiciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTFechaFin;
    private javax.swing.JTextField jTFechaInicio;
    private javax.swing.JTextField jTcupo;
    private javax.swing.JTextField jTcurso;
    private javax.swing.JTextField jTffechaPublicacion;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
