package com.edext.presentacion;

import com.edext.tools.CreaProgFormaUtils;
import com.edext.tools.CreaProgFormaHelper;
import com.edext.tools.cronometroHelper;
import com.edext.tools.Utils;
import java.time.LocalDate;
import javax.swing.JFormattedTextField;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author vdraco
 */
public class CreaPrograFormaForm extends javax.swing.JPanel {
    private final CreaProgFormaHelper Values=new CreaProgFormaHelper();
    private final CreaProgFormaUtils fecha=new CreaProgFormaUtils();
    private final cronometroHelper reloj;
    private LocalDate fechaRegistro;
    private LocalDate fechaInicio;
    private LocalDate fechaFin;
    private String descripcion;
    private String nombre;
    private final int IZQ_DER=0;
    private final int DER_IZQ=1;

    /**
     * Creates new form crearProgramaFormacion
     */

    public CreaPrograFormaForm() {
        initComponents();
        reloj=new cronometroHelper(400, jPError, jLErrorMsg, jBCreate);
        jPError.setVisible(false);
        jPNuevo.setVisible(false);
        fecha.assignFormato(jFfechaFin);
        fecha.assignFormato(jFfechaInicio);
        fecha.assignFormato(jFfechaPublic);
        jLista.setListData(Values.getList());
        setInactiveList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLista = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jBNew = new javax.swing.JButton();
        jPMaster = new javax.swing.JPanel();
        jPNuevo = new javax.swing.JPanel();
        jLnombre = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLfechaInicio = new javax.swing.JLabel();
        jFfechaInicio = new javax.swing.JFormattedTextField();
        jBfechaInicio = new javax.swing.JButton();
        jDfechaInicio = new com.toedter.calendar.JDateChooser();
        jLfechaFin = new javax.swing.JLabel();
        jFfechaFin = new javax.swing.JFormattedTextField();
        jBfechaFin = new javax.swing.JButton();
        jDfechaFin = new com.toedter.calendar.JDateChooser();
        jLfechaPublic = new javax.swing.JLabel();
        jFfechaPublic = new javax.swing.JFormattedTextField();
        jBfechaPublic = new javax.swing.JButton();
        jDfechaPublic = new com.toedter.calendar.JDateChooser();
        jLdescripcion = new javax.swing.JLabel();
        jSPdescripcion = new javax.swing.JScrollPane();
        jTAdescripcion = new javax.swing.JTextArea();
        jBCreate = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jPError = new javax.swing.JPanel();
        jLError = new javax.swing.JLabel();
        jLErrorMsg = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(620, 415));
        setPreferredSize(new java.awt.Dimension(620, 415));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLista.setFocusable(false);
        jLista.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jLista);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 181, 254));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Existentes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        jBNew.setText("Nuevo Programa");
        jBNew.addActionListener(this::jBNewActionPerformed);
        add(jBNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 160, -1));

        jPMaster.setFocusable(false);
        jPMaster.setMinimumSize(new java.awt.Dimension(540, 364));

        jPNuevo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPNuevoComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPNuevoComponentShown(evt);
            }
        });
        jPNuevo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLnombre.setText("Nombre ..........:");
        jLnombre.setFocusable(false);
        jLnombre.setRequestFocusEnabled(false);
        jPNuevo.add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, -1, -1));

        jTnombre.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jTnombre.setNextFocusableComponent(jFfechaInicio);
        jTnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTnombreFocusLost(evt);
            }
        });
        jPNuevo.add(jTnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 202, -1));

        jLfechaInicio.setText("Fecha de Inicio .......:");
        jLfechaInicio.setFocusable(false);
        jLfechaInicio.setRequestFocusEnabled(false);
        jPNuevo.add(jLfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 59, -1, -1));

        jFfechaInicio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFfechaInicio.setNextFocusableComponent(jFfechaFin);
        jFfechaInicio.addCaretListener(this::jFfechaInicioCaretUpdate);
        jFfechaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFfechaInicioFocusLost(evt);
            }
        });
        jPNuevo.add(jFfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 70, -1));

        jBfechaInicio.setText("......");
        jBfechaInicio.setFocusable(false);
        jBfechaInicio.setRequestFocusEnabled(false);
        jBfechaInicio.addActionListener(this::jBfechaInicioActionPerformed);
        jPNuevo.add(jBfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 32, 19));

        jDfechaInicio.setDateFormatString("ddMMyy");
        jDfechaInicio.setFocusable(false);
        jDfechaInicio.setOpaque(false);
        jDfechaInicio.setRequestFocusEnabled(false);
        jDfechaInicio.addPropertyChangeListener(this::jDfechaInicioPropertyChange);
        jPNuevo.add(jDfechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 65, 10, 10));

        jLfechaFin.setText("Fecha de Finalizacion ...:");
        jLfechaFin.setFocusable(false);
        jLfechaFin.setRequestFocusEnabled(false);
        jPNuevo.add(jLfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 101, -1, -1));

        jFfechaFin.setNextFocusableComponent(jFfechaPublic);
        jFfechaFin.addCaretListener(this::jFfechaFinCaretUpdate);
        jFfechaFin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFfechaFinFocusLost(evt);
            }
        });
        jPNuevo.add(jFfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 70, -1));

        jBfechaFin.setText("......");
        jBfechaFin.setFocusable(false);
        jBfechaFin.setRequestFocusEnabled(false);
        jBfechaFin.addActionListener(this::jBfechaFinActionPerformed);
        jPNuevo.add(jBfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 32, 19));

        jDfechaFin.addPropertyChangeListener(this::jDfechaFinPropertyChange);
        jPNuevo.add(jDfechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 105, 10, 10));

        jLfechaPublic.setText("Fecha de Publicacion ...:");
        jLfechaPublic.setFocusable(false);
        jLfechaPublic.setRequestFocusEnabled(false);
        jPNuevo.add(jLfechaPublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 143, -1, -1));

        jFfechaPublic.setNextFocusableComponent(jBCreate);
        jFfechaPublic.addCaretListener(this::jFfechaPublicCaretUpdate);
        jFfechaPublic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFfechaPublicFocusLost(evt);
            }
        });
        jPNuevo.add(jFfechaPublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 70, -1));

        jBfechaPublic.setText("......");
        jBfechaPublic.setFocusable(false);
        jBfechaPublic.setRequestFocusEnabled(false);
        jBfechaPublic.addActionListener(this::jBfechaPublicActionPerformed);
        jPNuevo.add(jBfechaPublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 32, 19));

        jDfechaPublic.addPropertyChangeListener(this::jDfechaPublicPropertyChange);
        jPNuevo.add(jDfechaPublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 145, 10, 10));

        jLdescripcion.setText("Descripcion ...:");
        jLdescripcion.setFocusable(false);
        jLdescripcion.setRequestFocusEnabled(false);
        jPNuevo.add(jLdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 182, -1, -1));

        jTAdescripcion.setColumns(20);
        jTAdescripcion.setRows(5);
        jTAdescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTAdescripcionFocusLost(evt);
            }
        });
        jSPdescripcion.setViewportView(jTAdescripcion);

        jPNuevo.add(jSPdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 270, 150));

        jBCreate.setBackground(new java.awt.Color(9, 104, 21));
        jBCreate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBCreate.setForeground(new java.awt.Color(254, 254, 254));
        jBCreate.setText("Crear");
        jBCreate.setNextFocusableComponent(jBCancel);
        jBCreate.addActionListener(this::jBCreateActionPerformed);
        jPNuevo.add(jBCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 210, -1));

        jBCancel.setBackground(new java.awt.Color(131, 46, 46));
        jBCancel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jBCancel.setText("Cancelar");
        jBCancel.setNextFocusableComponent(jTnombre);
        jBCancel.addActionListener(this::jBCancelActionPerformed);
        jPNuevo.add(jBCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        javax.swing.GroupLayout jPMasterLayout = new javax.swing.GroupLayout(jPMaster);
        jPMaster.setLayout(jPMasterLayout);
        jPMasterLayout.setHorizontalGroup(
            jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPMasterLayout.setVerticalGroup(
            jPMasterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMasterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 420, 410));

        jPError.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLError.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLError.setForeground(new java.awt.Color(255, 0, 0));
        jLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLError.setText("Ingreso Incorrecto");
        jLError.setFocusable(false);
        jPError.add(jLError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 181, 30));

        jLErrorMsg.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLErrorMsg.setForeground(new java.awt.Color(255, 0, 0));
        jLErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLErrorMsg.setFocusable(false);
        jPError.add(jLErrorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 181, 20));

        add(jPError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jPNuevoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPNuevoComponentShown
        jBNew.setEnabled(false);
        jTnombre.requestFocus();
    }//GEN-LAST:event_jPNuevoComponentShown

    private void jPNuevoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPNuevoComponentHidden
        jTnombre.setText("");
        jFfechaInicio.setText("");
        jFfechaFin.setText("");
        jFfechaPublic.setText("");
        jTAdescripcion.setText("");
        fechaRegistro=fechaInicio=fechaFin=null;
        descripcion=nombre=null;
        jBCreate.setEnabled(false);
        jBNew.setEnabled(true);
        reloj.kill();
    }//GEN-LAST:event_jPNuevoComponentHidden

    private void jBNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewActionPerformed
        jPNuevo.setVisible(true);
    }//GEN-LAST:event_jBNewActionPerformed

    private void jTnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombreFocusLost
        nombre=jTnombre.getText();
        jTnombre();
        refresh();
    }//GEN-LAST:event_jTnombreFocusLost

    private void jFfechaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFfechaInicioFocusLost
        if(jPNuevo.isVisible()){
            String tmp=jFfechaInicio.getText();
            if(fechaValidate(tmp, "Fecha de Inicio")){
                fechaInicio=Utils.str2LocalDate(tmp);
            }
            refresh();
        }
    }//GEN-LAST:event_jFfechaInicioFocusLost

    private void jFfechaFinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFfechaFinFocusLost
        if(jPNuevo.isVisible()){
            String tmp=jFfechaFin.getText();
            if(fechaValidate(tmp, "Fecha de Finalizacion")) fechaFin=Utils.str2LocalDate(tmp);
            refresh();
        }
    }//GEN-LAST:event_jFfechaFinFocusLost

    private void jFfechaPublicFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFfechaPublicFocusLost
        if(jPNuevo.isVisible()){
            String tmp=jFfechaPublic.getText();
            if(fechaValidate(tmp, "Fecha de Publicacion")){
                fechaRegistro=Utils.str2LocalDate(tmp);
            }
            refresh();
        }
    }//GEN-LAST:event_jFfechaPublicFocusLost

    private void jBfechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfechaInicioActionPerformed
        jDfechaInicio.getCalendarButton().doClick();
    }//GEN-LAST:event_jBfechaInicioActionPerformed

    private void jBfechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfechaFinActionPerformed
        jDfechaFin.getCalendarButton().doClick();
    }//GEN-LAST:event_jBfechaFinActionPerformed

    private void jBfechaPublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfechaPublicActionPerformed
        jDfechaPublic.getCalendarButton().doClick();
    }//GEN-LAST:event_jBfechaPublicActionPerformed

    private void jDfechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDfechaInicioPropertyChange
        if(jPNuevo.isVisible()){
            fechaInicio=Utils.date2locatDate(jDfechaInicio.getDate());
            fechaValidate(fechaInicio, Utils.date2locatDate(jDfechaFin.getDate()), jFfechaInicio, IZQ_DER);
            refresh();
        }
    }//GEN-LAST:event_jDfechaInicioPropertyChange

    private void jDfechaFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDfechaFinPropertyChange
        if(jPNuevo.isVisible()){
            fechaFin=Utils.date2locatDate(jDfechaFin.getDate());
            fechaValidate(fechaFin, Utils.date2locatDate(jDfechaInicio.getDate()), jFfechaFin, DER_IZQ);
            refresh();
        }
    }//GEN-LAST:event_jDfechaFinPropertyChange

    private void jDfechaPublicPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDfechaPublicPropertyChange
        if(jPNuevo.isVisible()){
            if(jDfechaPublic.getDate()!=null){
                fechaRegistro=Utils.date2locatDate(jDfechaPublic.getDate());
                jFfechaPublic.setText(Utils.Fecha.assignFormato(fechaRegistro));
                reloj.alarm(false, "Fecha de Publicacion");
            }
            refresh();
        }
    }//GEN-LAST:event_jDfechaPublicPropertyChange

    private void jFfechaInicioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFfechaInicioCaretUpdate
        if(jPNuevo.isVisible()){
            if(!Utils.Fecha.validate(jFfechaInicio.getText())) reloj.alarm(true, "Fecha de Inicio");
            else reloj.alarm(false, "Fecha de Inicio"); 
            refresh();
        }
    }//GEN-LAST:event_jFfechaInicioCaretUpdate

    private void jFfechaFinCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFfechaFinCaretUpdate
        if(jPNuevo.isVisible()){
            if(!Utils.Fecha.validate(jFfechaFin.getText())) reloj.alarm(true, "Fecha de Finalizacion");
            else reloj.alarm(false, "Fecha de Finalizacion");
            refresh();
        }
    }//GEN-LAST:event_jFfechaFinCaretUpdate

    private void jFfechaPublicCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jFfechaPublicCaretUpdate
        if(jPNuevo.isVisible()){
            if(!Utils.Fecha.validate(jFfechaPublic.getText())) reloj.alarm(true, "Fecha de Publicacion");
            else reloj.alarm(false, "Fecha de Publicacion");
            refresh();
        }
    }//GEN-LAST:event_jFfechaPublicCaretUpdate

    private void jBCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCreateActionPerformed
        String message;
        boolean flag=false;
        if (descripcion==null) message="La descripción se encuentra vacía,  ¿Desea continuar?";
        else message="Confirme creación de Programa de Edición";
        int tmp=confirm(message);
        if(tmp==0){
            try {
                flag=Values.setData(nombre, descripcion, fechaRegistro, fechaInicio, fechaFin);
                //System.out.println("Resultado de la transaccion ...: "+flag);
                message=jTnombre.getText();
                jPNuevo.setVisible(!flag);
            } catch (Exception ex) {
                showMessageDialog(this, "Nombre Existente");
                //System.out.println("Resultado de la Transaccion ...: "+flag);
                //System.getLogger(CreaPrograFormaForm.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            if(flag){
                Values.getLista().add(message);//  debug
                jLista.setListData(Values.getList());//   debug
            }
            
        }
    }//GEN-LAST:event_jBCreateActionPerformed

    private void jTAdescripcionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTAdescripcionFocusLost
        descripcion=jTAdescripcion.getText();
        refresh();
    }//GEN-LAST:event_jTAdescripcionFocusLost

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        if(confirm("Si cancela perderá los datos no guardados")==0)
            jPNuevo.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jTnombre(){
        if(jTnombre.getText().isEmpty()) reloj.alarm(true, "Nombre faltante");
        else{
            reloj.alarm(false, "Nombre faltante");
            if(Values.isExist(jTnombre.getText())){
                reloj.alarm(true, "Nombre Existente");
                //showMessageDialog(this, "Nombre Existente");
                jTnombre.requestFocus();
                jTnombre.setSelectionStart(0);
            }else reloj.alarm(false, "Nombre Existente");
        }
    }

    private boolean fechaValidate(String tmpFecha, String mensaje){
        boolean ret=Utils.Fecha.validate(tmpFecha);
        if(!ret) reloj.alarm(true, mensaje);
        else reloj.alarm(false, mensaje);
        return ret;
    }

    private boolean fechaValidate(LocalDate fecha1, LocalDate fecha2, JFormattedTextField obj, int modo){
        boolean flag=true;
        if(fecha1!=null){
            if(fecha2!=null)
                if(modo==IZQ_DER){
                    flag=Utils.Fecha.isCoherente(fecha1, fecha2);
                }else if(modo==DER_IZQ){
                    flag=Utils.Fecha.isCoherente(fecha2, fecha1);
                    obj.setText(Utils.Fecha.assignFormato(fecha2));
                }
            obj.setText(Utils.Fecha.assignFormato(fecha1));
            if(flag) reloj.alarm(false, "Fechas Invertidas");
            else reloj.alarm(true, "Fechas Invertidas");
            
        }
        return flag;
    }
    
    private void refresh(){
//        List<String> listDebuger=new ArrayList<>();
//        listDebuger.add(nombre);
//        listDebuger.add(descripcion);
//        if(fechaInicio!=null) listDebuger.add(fechaInicio.toString());
//        if(fechaFin!=null) listDebuger.add(fechaFin.toString());
//        if(fechaRegistro!=null) listDebuger.add(fechaRegistro.toString());
//        listDebuger=null;    
        //if(!jTnombre.getText().isEmpty() && !jFfechaInicio.getText().isEmpty() && !jFfechaFin.getText().isEmpty() && !jFfechaPublic.getText().isEmpty())
        //jBCreate.setEnabled(false);
        
        if((nombre!=null) && (fechaInicio!=null) && (fechaFin!=null)
        && (fechaRegistro!=null) && (reloj.getLista().length==0))
            jBCreate.setEnabled(true);
        else jBCreate.setEnabled(false);
        
    }
    
    private void setInactiveList(){
        jLista.setSelectionModel(new DefaultListSelectionModel(){
            @Override
            public void setSelectionInterval(int index0, int index1){}

            @Override
            public void addSelectionInterval(int index0, int index1){}
        });

    }
    
    private int confirm(String mensaje){
//        JButton botonSi = new JButton("         SI         ");
//        botonSi.setBackground(new Color(140, 6, 6)); // rojo pastel
//        botonSi.setForeground(Color.BLACK);
//        botonSi.setFont(new Font("Arial", Font.BOLD, 12));
//        JButton botonNo = new JButton("         NO         ");
//        botonNo.setBackground(new Color(41, 102, 49));  // verde pastel
//        botonNo.setForeground(Color.WHITE);
//        botonNo.setFont(new Font("Arial", Font.BOLD, 12));
//        Object[] opciones = { botonSi, botonNo };
//        botonSi=null;
//        botonNo=null;
//        return JOptionPane.showOptionDialog(
//                this, "La descripción se encuentra vacía,  ¿Desea continuar?", "Confirme acción", 
//                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, opciones, opciones[0]);
        return JOptionPane.showOptionDialog(
                this, mensaje, "Confirme acción", 
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBCreate;
    private javax.swing.JButton jBNew;
    private javax.swing.JButton jBfechaFin;
    private javax.swing.JButton jBfechaInicio;
    private javax.swing.JButton jBfechaPublic;
    private com.toedter.calendar.JDateChooser jDfechaFin;
    private com.toedter.calendar.JDateChooser jDfechaInicio;
    private com.toedter.calendar.JDateChooser jDfechaPublic;
    private javax.swing.JFormattedTextField jFfechaFin;
    private javax.swing.JFormattedTextField jFfechaInicio;
    private javax.swing.JFormattedTextField jFfechaPublic;
    private javax.swing.JLabel jLError;
    private javax.swing.JLabel jLErrorMsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLdescripcion;
    private javax.swing.JLabel jLfechaFin;
    private javax.swing.JLabel jLfechaInicio;
    private javax.swing.JLabel jLfechaPublic;
    private javax.swing.JList<String> jLista;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JPanel jPError;
    private javax.swing.JPanel jPMaster;
    private javax.swing.JPanel jPNuevo;
    private javax.swing.JScrollPane jSPdescripcion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAdescripcion;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
