package com.edext.presentacion;

import com.edext.tools.indexHelper;
import java.awt.Component;
import javax.swing.JDesktopPane;


public class index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(index.class.getName());
    private javax.swing.JInternalFrame ventanaAltaUsuario;
    private javax.swing.JInternalFrame ventanaConsultaUsuario;
    private javax.swing.JInternalFrame ventanaModificarUsuario;
    private indexHelper form;
    
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        form=new indexHelper(dpIndex);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpIndex = new javax.swing.JDesktopPane();
        mbIndex = new javax.swing.JMenuBar();
        mInstitutos = new javax.swing.JMenu();
        miInstituto = new javax.swing.JMenuItem();
        mUsuarios = new javax.swing.JMenu();
        miAltaUsuario = new javax.swing.JMenuItem();
        miConsultaUsuario = new javax.swing.JMenuItem();
        miModificarUsuario = new javax.swing.JMenuItem();
        mCursos = new javax.swing.JMenu();
        altaCurso = new javax.swing.JMenuItem();
        editarCurso = new javax.swing.JMenuItem();
        consultaCurso = new javax.swing.JMenuItem();
        jmInscripcionEdicion = new javax.swing.JMenuItem();
        jmConsultaEdicion = new javax.swing.JMenuItem();
        mPrograma = new javax.swing.JMenu();
        jmCrearPrograma = new javax.swing.JMenuItem();
        miAgregarPrograma = new javax.swing.JMenuItem();
        miConsultaPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpIndexLayout = new javax.swing.GroupLayout(dpIndex);
        dpIndex.setLayout(dpIndexLayout);
        dpIndexLayout.setHorizontalGroup(
            dpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        dpIndexLayout.setVerticalGroup(
            dpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        mInstitutos.setText("Institutos");

        miInstituto.setText("Instituto");
        miInstituto.addActionListener(this::miInstitutoActionPerformed);
        mInstitutos.add(miInstituto);

        mbIndex.add(mInstitutos);

        mUsuarios.setText("Usuarios");

        miAltaUsuario.setText("Nuevo Usuario");
        miAltaUsuario.addActionListener(this::miAltaUsuarioActionPerformed);
        mUsuarios.add(miAltaUsuario);

        miConsultaUsuario.setText("Consulta Usuario");
        miConsultaUsuario.addActionListener(this::miConsultaUsuarioActionPerformed);
        mUsuarios.add(miConsultaUsuario);

        miModificarUsuario.setText("Modificar Usuario");
        miModificarUsuario.addActionListener(this::miModificarUsuarioActionPerformed);
        mUsuarios.add(miModificarUsuario);

        mbIndex.add(mUsuarios);

        mCursos.setText("Cursos");

        altaCurso.setText("Alta curso");
        altaCurso.addActionListener(this::altaCursoActionPerformed);
        mCursos.add(altaCurso);

        editarCurso.setText("Editar curso");
        editarCurso.addActionListener(this::editarCursoActionPerformed);
        mCursos.add(editarCurso);

        consultaCurso.setText("Consulta curso");
        consultaCurso.addActionListener(this::consultaCursoActionPerformed);
        mCursos.add(consultaCurso);

        jmInscripcionEdicion.setText("Inscripcion a edicion");
        jmInscripcionEdicion.addActionListener(this::jmInscripcionEdicionActionPerformed);
        mCursos.add(jmInscripcionEdicion);

        jmConsultaEdicion.setText("Consulta de Edicion");
        jmConsultaEdicion.addActionListener(this::jmConsultaEdicionActionPerformed);
        mCursos.add(jmConsultaEdicion);

        mbIndex.add(mCursos);

        mPrograma.setText("ProgramaFormacion");

        jmCrearPrograma.setText("Crear Programa");
        jmCrearPrograma.addActionListener(this::jmCrearProgramaActionPerformed);
        mPrograma.add(jmCrearPrograma);

        miAgregarPrograma.setText("Agregar curso a programa");
        miAgregarPrograma.addActionListener(this::miAgregarProgramaActionPerformed);
        mPrograma.add(miAgregarPrograma);

        miConsultaPrograma.setText("Consulta Programa");
        miConsultaPrograma.addActionListener(this::miConsultaProgramaActionPerformed);
        mPrograma.add(miConsultaPrograma);

        mbIndex.add(mPrograma);

        setJMenuBar(mbIndex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpIndex)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpIndex)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInstitutoActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Institutos",true,true,true,true);
        internalFrame.getContentPane().add(new institutos());
        internalFrame.pack();
        this.dpIndex.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miInstitutoActionPerformed
    //Abrir menu Nuevo Usuario
    private void miAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaUsuarioActionPerformed
        // Si la ventana ya existe y sigue abierta
        if (ventanaAltaUsuario != null && ventanaAltaUsuario.isDisplayable()) {
            try {
                ventanaAltaUsuario.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                
            }
            //trae la ventana al frente
            ventanaAltaUsuario.toFront();
            return;
        }

        // Crear la ventana solamente si no existe
        ventanaAltaUsuario = new javax.swing.JInternalFrame(
                "Nuevo Usuario", true, true, false, false);
        
        AltaUsuario formulario = new AltaUsuario();

        ventanaAltaUsuario.getContentPane().add(formulario);
        
        ventanaAltaUsuario.pack();
        
        dpIndex.add(ventanaAltaUsuario);
        ventanaAltaUsuario.setVisible(true);

        // Cuando se cierre, se libera la referencia
        ventanaAltaUsuario.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(
                            javax.swing.event.InternalFrameEvent e) {
                        ventanaAltaUsuario = null;
                    }
                }
        );

    }//GEN-LAST:event_miAltaUsuarioActionPerformed
    //Abrir menuCosnulta usuario
    private void miConsultaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaUsuarioActionPerformed
        // Si la ventana ya existe y sigue abierta
        if (ventanaConsultaUsuario != null && ventanaConsultaUsuario.isDisplayable()) {
            try {
                ventanaConsultaUsuario.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                
            }
            //trae la ventana al frente
            ventanaConsultaUsuario.toFront();
            return;
        }

        // Crear la ventana solamente si no existe
        ventanaConsultaUsuario = new javax.swing.JInternalFrame(
                "Consulta Usuario", true, true, false, false);

        ventanaConsultaUsuario.getContentPane().add(new ConsultaUsuario());
        ventanaConsultaUsuario.pack();

        dpIndex.add(ventanaConsultaUsuario);
        ventanaConsultaUsuario.setVisible(true);

        // Cuando se cierre, se libera la referencia
        ventanaConsultaUsuario.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(
                            javax.swing.event.InternalFrameEvent e) {
                        ventanaConsultaUsuario = null;
                    }
                }
        );
    }//GEN-LAST:event_miConsultaUsuarioActionPerformed

    private void miModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarUsuarioActionPerformed
            // Si la ventana ya existe y sigue abierta
        if (ventanaModificarUsuario != null && ventanaModificarUsuario.isDisplayable()) {
            try {
                ventanaModificarUsuario.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
            }

            ventanaModificarUsuario.toFront();
            return;
        }

        // Crear la ventana solamente si no existe
        ventanaModificarUsuario = new javax.swing.JInternalFrame(
                "Modificar Usuario", true, true, false, false);

        ventanaModificarUsuario.getContentPane().add(new ModificarUsuario());
        ventanaModificarUsuario.pack();

        dpIndex.add(ventanaModificarUsuario);
        ventanaModificarUsuario.setVisible(true);

        // Cuando se cierre, liberar la referencia
        ventanaModificarUsuario.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(
                            javax.swing.event.InternalFrameEvent e) {
                        ventanaModificarUsuario = null;
                    }
                }
        );
    }//GEN-LAST:event_miModificarUsuarioActionPerformed

    private void miAgregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarProgramaActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Agregar curso a programa",true,true,true,true);
        internalFrame.getContentPane().add(new agregarCursoPrograma());
        internalFrame.pack();
        this.dpIndex.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miAgregarProgramaActionPerformed

    private void miConsultaProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaProgramaActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Consulta programas",true,true,true,true);
        internalFrame.getContentPane().add(new consultaPrograma());
        internalFrame.pack();
        this.dpIndex.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miConsultaProgramaActionPerformed

    private void altaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaCursoActionPerformed
        altaCurso ventanaAlta = new altaCurso();
        ventanaAlta.setSize(600, 500);
        this.dpIndex.add(ventanaAlta);
        ventanaAlta.setVisible(true);
    }//GEN-LAST:event_altaCursoActionPerformed

    private void editarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCursoActionPerformed
        editarCurso ventanaEditar = new editarCurso();
        ventanaEditar.setSize(600, 500);
        this.dpIndex.add(ventanaEditar);
        ventanaEditar.setVisible(true);
    }//GEN-LAST:event_editarCursoActionPerformed

    private void consultaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaCursoActionPerformed
        consultaCurso ventanaConsulta = new consultaCurso();
        ventanaConsulta.setSize(600, 500);
        this.dpIndex.add(ventanaConsulta);
        ventanaConsulta.setVisible(true);
    }//GEN-LAST:event_consultaCursoActionPerformed
    private void jmConsultaEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultaEdicionActionPerformed
        form.cargarPanel("Consulta de Edicion de Curso", new consultaEdicionCurso(), true, false);
    }//GEN-LAST:event_jmConsultaEdicionActionPerformed

    private void jmInscripcionEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmInscripcionEdicionActionPerformed
        form.cargarPanel("Inscripcion a Edicion de Curso", new inscripcionEdicionCurso(), true, false);
    }//GEN-LAST:event_jmInscripcionEdicionActionPerformed

    private void jmCrearProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCrearProgramaActionPerformed
        form.cargarPanel("Crear Programa de Formacion", new CreaPrograFormaForm(), true, false);
    }//GEN-LAST:event_jmCrearProgramaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new index().setVisible(true));
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altaCurso;
    private javax.swing.JMenuItem consultaCurso;
    private javax.swing.JDesktopPane dpIndex;
    private javax.swing.JMenuItem editarCurso;
    private javax.swing.JMenuItem jmConsultaEdicion;
    private javax.swing.JMenuItem jmCrearPrograma;
    private javax.swing.JMenuItem jmInscripcionEdicion;
    private javax.swing.JMenu mCursos;
    private javax.swing.JMenu mInstitutos;
    private javax.swing.JMenu mPrograma;
    private javax.swing.JMenu mUsuarios;
    private javax.swing.JMenuBar mbIndex;
    private javax.swing.JMenuItem miAgregarPrograma;
    private javax.swing.JMenuItem miAltaUsuario;
    private javax.swing.JMenuItem miConsultaPrograma;
    private javax.swing.JMenuItem miConsultaUsuario;
    private javax.swing.JMenuItem miInstituto;
    private javax.swing.JMenuItem miModificarUsuario;
    // End of variables declaration//GEN-END:variables
}
