package com.edext.presentacion;


public class index extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(index.class.getName());
    private javax.swing.JInternalFrame ventanaAltaUsuario;
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpIndex = new javax.swing.JDesktopPane();
        mbIndex = new javax.swing.JMenuBar();
        mInstitutos = new javax.swing.JMenu();
        miInstituto = new javax.swing.JMenuItem();
        mUsuarios = new javax.swing.JMenu();
        miAltaUsuario = new javax.swing.JMenuItem();
        mCursos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dpIndexLayout = new javax.swing.GroupLayout(dpIndex);
        dpIndex.setLayout(dpIndexLayout);
        dpIndexLayout.setHorizontalGroup(
            dpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 993, Short.MAX_VALUE)
        );
        dpIndexLayout.setVerticalGroup(
            dpIndexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        mInstitutos.setText("Institutos");

        miInstituto.setText("Instituto");
        miInstituto.addActionListener(this::miInstitutoActionPerformed);
        mInstitutos.add(miInstituto);

        mbIndex.add(mInstitutos);

        mUsuarios.setText("Usuarios");

        miAltaUsuario.setText("Nuevo Usuario");
        miAltaUsuario.addActionListener(this::miAltaUsuarioActionPerformed);
        mUsuarios.add(miAltaUsuario);

        mbIndex.add(mUsuarios);

        mCursos.setText("Cursos");
        mbIndex.add(mCursos);

        setJMenuBar(mbIndex);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpIndex)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpIndex)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miInstitutoActionPerformed
        javax.swing.JInternalFrame internalFrame = new javax.swing.JInternalFrame("Institutos",true,true,true,true);
        internalFrame.getContentPane().add(new institutos());
        internalFrame.pack();
        this.dpIndex.add(internalFrame);
        internalFrame.setVisible(true);
    }//GEN-LAST:event_miInstitutoActionPerformed

    private void miAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAltaUsuarioActionPerformed
        // Si la ventana ya existe y sigue abierta
        if (ventanaAltaUsuario != null && ventanaAltaUsuario.isDisplayable()) {
            try {
                ventanaAltaUsuario.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                
            }
            //trae la ventana al frente
            ventanaAltaUsuario.toFront();
            return;
        }

        // Crear la ventana solamente si no existe
        ventanaAltaUsuario = new javax.swing.JInternalFrame(
                "Nuevo Usuario", true, true, false, false);

        ventanaAltaUsuario.getContentPane().add(new AltaUsuario());
        ventanaAltaUsuario.pack();

        dpIndex.add(ventanaAltaUsuario);
        ventanaAltaUsuario.setVisible(true);

        // Cuando se cierre, se libera la referencia
        ventanaAltaUsuario.addInternalFrameListener(
                new javax.swing.event.InternalFrameAdapter() {
                    @Override
                    public void internalFrameClosed(
                            javax.swing.event.InternalFrameEvent e) {
                        ventanaAltaUsuario = null;
                    }
                }
        );

    }//GEN-LAST:event_miAltaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new index().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpIndex;
    private javax.swing.JMenu mCursos;
    private javax.swing.JMenu mInstitutos;
    private javax.swing.JMenu mUsuarios;
    private javax.swing.JMenuBar mbIndex;
    private javax.swing.JMenuItem miAltaUsuario;
    private javax.swing.JMenuItem miInstituto;
    // End of variables declaration//GEN-END:variables
}
