package com.edext.presentacion;


import com.edext.tools.ConsultaEdicionHelper;
import com.edext.tools.InscripcionEdicionHelper;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import org.tinylog.Logger;

/**
 *
 * @author vdraco
 */
public class InscripcionEdicion extends javax.swing.JPanel {
    private String oldInscriptoSelect="", oldCandidatoSelect="", estadoCruce;
    private final int INSCRIPTOS=1, CANDIDATOS=2;
    /**
     * Creates new form InscEditCursoForm
     */
    public InscripcionEdicion() {
        initComponents();
        jPCursos.setVisible(false);
        jPEdiciones.setVisible(false);
        jPEInscriptos.setVisible(false);
        jPECandidatos.setVisible(false);
        jBEst_Cand.setVisible(false);
        jPEstudiantes.setVisible(false);
        jBshowCandidatos.setVisible(false);
        jBconfirmar.setVisible(false);
        jBcancelar.setVisible(false);
        cargaIntituto();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLInstituto = new javax.swing.JLabel();
        jCInstituto = new javax.swing.JComboBox();
        jPCursos = new javax.swing.JPanel();
        jSCursos = new javax.swing.JScrollPane();
        jLCursos = new javax.swing.JList<>();
        jPEdiciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLEdiciones = new javax.swing.JList<>();
        jPEstudiantes = new javax.swing.JPanel();
        jPEInscriptos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLInscriptos = new javax.swing.JList<>();
        jPECandidatos = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLCandidatos = new javax.swing.JList<>();
        jBshowCandidatos = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBconfirmar = new javax.swing.JButton();
        jBEst_Cand = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setMinimumSize(new java.awt.Dimension(735, 408));
        setPreferredSize(new java.awt.Dimension(735, 408));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLInstituto.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLInstituto.setText("Instituto ...:");
        add(jLInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, -1, -1));

        jCInstituto.addItemListener(this::jCInstitutoItemStateChanged);
        jCInstituto.addActionListener(this::jCInstitutoActionPerformed);
        add(jCInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 12, 235, -1));

        jPCursos.setMinimumSize(new java.awt.Dimension(155, 330));
        jPCursos.setPreferredSize(new java.awt.Dimension(152, 310));
        jPCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSCursos.setFocusable(false);
        jSCursos.setPreferredSize(new java.awt.Dimension(151, 300));

        jLCursos.addListSelectionListener(this::jLCursosValueChanged);
        jSCursos.setViewportView(jLCursos);

        jPCursos.add(jSCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(jPCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, -1, 330));

        jPEdiciones.setPreferredSize(new java.awt.Dimension(190, 270));
        jPEdiciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLEdiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLEdicionesMouseClicked(evt);
            }
        });
        jLEdiciones.addListSelectionListener(this::jLEdicionesValueChanged);
        jScrollPane2.setViewportView(jLEdiciones);

        jPEdiciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 300));

        add(jPEdiciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 55, 172, 330));

        jPEstudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPEInscriptos.setPreferredSize(new java.awt.Dimension(190, 270));
        jPEInscriptos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLInscriptos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLInscriptosMouseReleased(evt);
            }
        });
        jLInscriptos.addListSelectionListener(this::jLInscriptosValueChanged);
        jScrollPane4.setViewportView(jLInscriptos);

        jPEInscriptos.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 300));

        jPEstudiantes.add(jPEInscriptos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 172, 310));

        jPECandidatos.setPreferredSize(new java.awt.Dimension(190, 270));
        jPECandidatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLCandidatosMouseReleased(evt);
            }
        });
        jLCandidatos.addListSelectionListener(this::jLCandidatosValueChanged);
        jScrollPane5.setViewportView(jLCandidatos);

        jPECandidatos.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 300));

        jPEstudiantes.add(jPECandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 43, 172, 310));

        jBshowCandidatos.setText("Mostrar Cantidatos");
        jBshowCandidatos.addActionListener(this::jBshowCandidatosActionPerformed);
        jPEstudiantes.add(jBshowCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 172, -1));

        jBcancelar.setText("Cancelar");
        jPEstudiantes.add(jBcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        jBconfirmar.setText("Confirmar");
        jPEstudiantes.add(jBconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, -1));

        jBEst_Cand.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jBEst_Cand.setText("<<");
        jBEst_Cand.setMaximumSize(new java.awt.Dimension(42, 338));
        jBEst_Cand.setMinimumSize(new java.awt.Dimension(42, 338));
        jBEst_Cand.setPreferredSize(new java.awt.Dimension(42, 338));
        jBEst_Cand.addActionListener(this::jBEst_CandActionPerformed);
        jPEstudiantes.add(jBEst_Cand, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 43, 44, 300));

        add(jPEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 12, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jCInstitutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCInstitutoItemStateChanged
        jPEdiciones.setVisible(false);
        jPCursos.setVisible(true);
    }//GEN-LAST:event_jCInstitutoItemStateChanged

    private void jCInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCInstitutoActionPerformed
        jPEstudiantes.setVisible(false);
        refreschCombo();
        //jPEdiciones.setVisible(false);
        //jPCursos.setVisible(true);
    }//GEN-LAST:event_jCInstitutoActionPerformed

    private void jLCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLCursosValueChanged
        if(!evt.getValueIsAdjusting()){
            jPEInscriptos.setVisible(false);
            if(jLCursos.getSelectedValue()!=null){
                jLEdiciones.setListData((new ConsultaEdicionHelper()).getListaEdiciones(jLCursos.getSelectedValue()));
                jPEdiciones.setVisible(true);
            }else jPEdiciones.setVisible(false);
        }

    }//GEN-LAST:event_jLCursosValueChanged

    private void jLEdicionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLEdicionesValueChanged
        if(!evt.getValueIsAdjusting())
            jPECandidatos.setVisible(false);
            jBEst_Cand.setVisible(false);
            if(jLEdiciones.getSelectedValue()!=null){
                loadEstudiantes(jLEdiciones.getSelectedValue());
                jBshowCandidatos.setVisible(true);
            }else jBshowCandidatos.setVisible(false);
    }//GEN-LAST:event_jLEdicionesValueChanged

    private void jLInscriptosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLInscriptosValueChanged
        
//        if(!evt.getValueIsAdjusting()){
//            Logger.debug("Seleccionado : {}", jLInscriptos.getSelectedValue());
//            if(jLInscriptos.getSelectedValue()!=oldInscriptoSelec){
//
//                if(jLCandidatos.getSelectedValue()==null){
//                    jBEst_Cand.setText(">>");
//                }
//                jBEst_Cand.setVisible(true);
//                oldInscriptoSelec=jLInscriptos.getSelectedValue();
//            }else{
//                oldInscriptoSelec="";
//                jLInscriptos.clearSelection();
//                if(jLCandidatos.getSelectedValue()==null){
//                    jBEst_Cand.setText("  ");
//                    
//                }else{
//                    jBEst_Cand.setText("<<");
//                }
//            }
//        }            
    }//GEN-LAST:event_jLInscriptosValueChanged

    private void jLCandidatosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLCandidatosValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jLCandidatosValueChanged

    private void jBshowCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBshowCandidatosActionPerformed
        loadCandidatos(jLEdiciones.getSelectedValue());
    }//GEN-LAST:event_jBshowCandidatosActionPerformed

    private void jLEdicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLEdicionesMouseClicked

    }//GEN-LAST:event_jLEdicionesMouseClicked

    private void jLInscriptosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInscriptosMouseReleased
        conmutarBoton(jLInscriptos, jLCandidatos, INSCRIPTOS, jBEst_Cand);
        if(jPECandidatos.isVisible()) jBEst_Cand.setVisible(true);
        else jBEst_Cand.setVisible(false);
    }//GEN-LAST:event_jLInscriptosMouseReleased

    private void jLCandidatosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCandidatosMouseReleased
        conmutarBoton(jLCandidatos, jLInscriptos, CANDIDATOS, jBEst_Cand);
    }//GEN-LAST:event_jLCandidatosMouseReleased

    private void jBEst_CandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEst_CandActionPerformed
        operacion();
    }//GEN-LAST:event_jBEst_CandActionPerformed


    private void operacion(){
        ArrayList<String> lista, listaCan;
        DefaultListModel<String> modeloIns, modeloCan;
        String nomEstudiante;
        if ("<<".equals(jBEst_Cand.getText())){
            nomEstudiante=jLCandidatos.getSelectedValue();
            try {
                new InscripcionEdicionHelper().setInscripcion(nomEstudiante, jLEdiciones.getSelectedValue());
                lista=new ArrayList<>();
                modeloIns=new DefaultListModel<>();
                for(int i = 0; i < jLInscriptos.getModel().getSize(); i++) lista.add(jLInscriptos.getModel().getElementAt(i));
                lista.add(nomEstudiante); 
                for(String elemento : lista) modeloIns.addElement(elemento);
                jLInscriptos.setModel(modeloIns);
                modeloCan=new DefaultListModel<>();
                lista.clear();
                for(int i = 0; i < jLCandidatos.getModel().getSize(); i++) lista.add(jLCandidatos.getModel().getElementAt(i));
                lista.remove(nomEstudiante);
                modeloCan=new DefaultListModel<>();
                for(String elemento : lista) modeloCan.addElement(elemento);
                jLCandidatos.setModel(modeloCan);
            } catch (Exception ex) {
                Logger.error(ex);
            }
        }else if (">>".equals(jBEst_Cand.getText())){
          nomEstudiante=jLInscriptos.getSelectedValue();
            try {
                new InscripcionEdicionHelper().detInscripcion(nomEstudiante, jLEdiciones.getSelectedValue());
                lista=new ArrayList<>();
                modeloIns=new DefaultListModel<>();
                for(int i = 0; i < jLCandidatos.getModel().getSize(); i++) lista.add(jLCandidatos.getModel().getElementAt(i));
                lista.add(nomEstudiante); 
                for(String elemento : lista) modeloIns.addElement(elemento);
                jLCandidatos.setModel(modeloIns);
                modeloCan=new DefaultListModel<>();
                lista.clear();
                for(int i = 0; i < jLInscriptos.getModel().getSize(); i++) lista.add(jLInscriptos.getModel().getElementAt(i));
                lista.remove(nomEstudiante);
                modeloCan=new DefaultListModel<>();
                for(String elemento : lista) modeloCan.addElement(elemento);
                jLInscriptos.setModel(modeloCan);
            } catch (Exception ex) {
                Logger.error(ex);
            }
        }
    }
    
    private void conmutarBoton(JList Principal, JList Secundario, int memoria, JButton Boton){
        Object  tmpObj1 = Principal.getSelectedValue();
        String  principal = tmpObj1!=null?tmpObj1.toString():"",
                oldSelect=memoria==INSCRIPTOS?this.oldInscriptoSelect:this.oldCandidatoSelect;
        Logger.debug("Seleccionado : {} - anterior : {}", Principal.getSelectedValue(), oldSelect);
        if(Secundario.getSelectedValue()!=null && Principal.getSelectedValue()!=null){
            if(!"X".equals(Boton.getText())) estadoCruce=Boton.getText();
            Boton.setText("X");
            Logger.debug("seleccionado ambos - estado : {}",estadoCruce);
            if(!oldSelect.equals(principal)){
                if(memoria==INSCRIPTOS)
                    oldInscriptoSelect=principal;
                else
                    oldCandidatoSelect=principal;
                Logger.debug("seleccionado distinto - estado {}",estadoCruce);
            }else{
                Logger.debug("seleccionado igual - estado {}",estadoCruce);
                    if(memoria==INSCRIPTOS){
                        Boton.setText("<<");
                        oldInscriptoSelect="";
                    }else{
                        Boton.setText(">>");
                        oldCandidatoSelect="";
                    }
                Principal.clearSelection();
            }
        }else{
            if(!oldSelect.equals(principal)){
                if(Secundario.getSelectedValue()==null){
                    if(memoria==INSCRIPTOS)
                        Boton.setText(">>");
                    else
                        Boton.setText("<<");
                }
                Boton.setVisible(true);
                if(memoria==INSCRIPTOS)
                    oldInscriptoSelect=principal;
                else
                    oldCandidatoSelect=principal;
            }else{
                if(memoria==INSCRIPTOS)
                    oldInscriptoSelect="";
                else
                    oldCandidatoSelect="";
                Principal.clearSelection();
                if(Secundario.getSelectedValue()==null)
                    Boton.setText("  ");
                else{
                    if(memoria==INSCRIPTOS)
                        Boton.setText("<<");
                    else
                        Boton.setText(">>");

                }
            }
        }
    }
    
    private void loadEstudiantes(String nombre){
        InscripcionEdicionHelper ins=new InscripcionEdicionHelper();
        jLInscriptos.setListData(ins.getEstudiantesInscriptos(nombre));
        jPEInscriptos.setVisible(true);
        jPEstudiantes.setVisible(true);
        if(jPECandidatos.isVisible()) jBEst_Cand.setVisible(true);
        else jBEst_Cand.setVisible(false);
        //jPECandidatos.setVisible(true);
        ins=null;
    }
    private void loadCandidatos(String nombre){
        InscripcionEdicionHelper cand=new InscripcionEdicionHelper();
        jLCandidatos.setListData(cand.getEstudiantesCandidatos(nombre));
        jBEst_Cand.setVisible(true);
        jPECandidatos.setVisible(true);
        //jBconfirmar.setVisible(true);
        //jBcancelar.setVisible(true);        
    }
    
    private void refreschCombo(){
        ConsultaEdicionHelper tmpSet=new ConsultaEdicionHelper();
        String[] tmp=tmpSet.getListCursos(jCInstituto.getSelectedItem().toString());
        if(tmp.length==0) jPEdiciones.setVisible(false);
        jLCursos.setListData(tmp);
        jPCursos.setVisible(true);
        tmpSet=null;
    }
    private void cargaIntituto(){
        ConsultaEdicionHelper hlp=new ConsultaEdicionHelper();
        DefaultComboBoxModel<String> tmp=new DefaultComboBoxModel<>();
        String[] data=hlp.getListInstitutos();
        Logger.debug("tamaño : {}", data.length);
        if(data.length>0){
            for(String nom : data) tmp.addElement(nom);
            jCInstituto.setModel(tmp);
            jCInstituto.setSelectedIndex(0);
        }else Logger.debug("Intitutos sin datos...");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEst_Cand;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBconfirmar;
    private javax.swing.JButton jBshowCandidatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCInstituto;
    private javax.swing.JList<String> jLCandidatos;
    private javax.swing.JList<String> jLCursos;
    private javax.swing.JList<String> jLEdiciones;
    private javax.swing.JList<String> jLInscriptos;
    private javax.swing.JLabel jLInstituto;
    private javax.swing.JPanel jPCursos;
    private javax.swing.JPanel jPECandidatos;
    private javax.swing.JPanel jPEInscriptos;
    private javax.swing.JPanel jPEdiciones;
    private javax.swing.JPanel jPEstudiantes;
    private javax.swing.JScrollPane jSCursos;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
