/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.edext.presentacion;

import com.edext.datatypes.DtUsuario;
import com.edext.logica.Fabrica;
import com.edext.logica.IControlador;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ModificarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ModifcarUsuario
     */
    
    private List<DtUsuario> usuarios;
    private AltaUsuario formularioUsuario;
    
    public ModificarUsuario() {
        initComponents();
        
        formularioUsuario = new AltaUsuario(1);

        panModificar.setLayout(new BorderLayout());
        panModificar.add(formularioUsuario, BorderLayout.CENTER);
        listarUsuarios();
        
    }
    private void listarUsuarios(){
        try{
            IControlador ic = Fabrica.getInstance().getIControlador();

            usuarios = ic.listarUsuarios();

            DefaultListModel<String> model = new DefaultListModel<>();

            for (DtUsuario aux: usuarios){
                model.addElement(aux.getNickname());
            }

            lisUsuario.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(
                this,
                "Error al actualizar la tabla: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lisUsuario = new javax.swing.JList<>();
        panModificar = new javax.swing.JPanel();

        lisUsuario.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lisUsuario.addListSelectionListener(this::lisUsuarioValueChanged);
        jScrollPane1.setViewportView(lisUsuario);

        javax.swing.GroupLayout panModificarLayout = new javax.swing.GroupLayout(panModificar);
        panModificar.setLayout(panModificarLayout);
        panModificarLayout.setHorizontalGroup(
            panModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );
        panModificarLayout.setVerticalGroup(
            panModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
            .addComponent(panModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lisUsuarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lisUsuarioValueChanged
        
        if (!evt.getValueIsAdjusting()) {

            int indice = lisUsuario.getSelectedIndex();

            if (indice != -1) {
                DtUsuario usuario = usuarios.get(indice);

                formularioUsuario.cargarFormulario(usuario);
            }
        }        
    }//GEN-LAST:event_lisUsuarioValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lisUsuario;
    private javax.swing.JPanel panModificar;
    // End of variables declaration//GEN-END:variables

 }
