# a definir
# file
# shared file


#writer.file     = ${user.home}/.edEXT/logs/reporte-{date: dd-MM-yyyy}.log
# Sintaxis oficial correcta para propiedades de Java (como user.home):


writer          = rolling file
writer.file     = #{user.home}/.edEXT/logs/reporte-{date: dd-MM-yyyy}.log
writer.policies = daily
writer.level    = debug
writer.format   = {date: HH:mm:ss} {level} [{thread}]->{class}->{method} := {message}
writer.charset  = UTF-8
writer.buffered = true
writer.backups  = 90
writingthread   = true
locale          = es_UY

# a definir
# startup
# daily

# en produccion cambiarlo a
#level           = info
# o
#level           = warn

