writer          = rolling file
writer.file     = #{user.home}/.edEXT/logs/Central-{date: dd-MM-yyyy}.log
writer.policies = daily
writer.level    = debug
writer.format   = {date: HH:mm:ss} {level} [{thread}]->{class}->{method} := {message}
writer.charset  = UTF-8
writer.buffered = true
writer.backups  = 90
writingthread   = true
locale          = es_UY

# en produccion cambiarlo a
#level           = info
# o
#level           = warn

